import type { Metadata } from "next";
import MainComponent from "./MainComponent";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#171717]">
        <MainComponent>{children}</MainComponent>
      </body>
    </html>
  );
}
